version: '3.8'

services:
  database:
    image: postgres
    container_name: database
    restart: unless-stopped
    env_file: ./docker/postgres/.env
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  php-apache:
    container_name: php-apache
    build:
      context: ./docker/php
    ports:
        - '8080:80'
    volumes:
      - ./src:/var/www/app
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database